import os

class Creator:
    def create_project(self, name):
        os.makedirs(name, exist_ok=True)
        with open(f"{name}/README.md", "w") as f:
            f.write(f"# {name}\nGenerated by Synthetic Intelligence")
